# config/compliance_rules.yaml
open_banking:
  required_fields:
    - sort_code
    - account_number
    - consent_status
  validation_rules:
    sort_code: "^[0-9]{2}-[0-9]{2}-[0-9]{2}$"
    account_number: "^[0-9]{8}$"

kyc:
  required_fields:
    - customer_id
    - risk_rating
    - id_verified
  allowed_values:
    risk_rating: ["low", "medium", "high"]
    id_verified: [true, false]

global:
  validate_pii: true
  auto_anonymize: true